export const ADD_COURSES = 'ADD_COURSES';
export const COURSES_LOADING = 'COURSES_LOADING';
export const COURSES_FAILED = 'COURSES_FAILED';
export const ADD_TEACHERS = 'ADD_TEACHERS';
export const TEACHERS_LOADING = 'TEACHERS_LOADING';
export const TEACHERS_FAILED = 'TEACHERS_FAILED';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';